#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : colord-kde
Version  : 0.5.0
Release  : 1
URL      : https://download.kde.org/stable/colord-kde/0.5.0/src/colord-kde-0.5.0.tar.xz
Source0  : https://download.kde.org/stable/colord-kde/0.5.0/src/colord-kde-0.5.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: colord-kde-bin = %{version}-%{release}
Requires: colord-kde-data = %{version}-%{release}
Requires: colord-kde-lib = %{version}-%{release}
Requires: colord-kde-license = %{version}-%{release}
Requires: colord-kde-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(xcb) xcb-util-cursor-dev xcb-util-image-dev xcb-util-keysyms-dev xcb-util-renderutil-dev xcb-util-wm-dev xcb-util-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : pkgconfig(lcms2)
BuildRequires : plasma-framework-dev

%description
No detailed description available

%package bin
Summary: bin components for the colord-kde package.
Group: Binaries
Requires: colord-kde-data = %{version}-%{release}
Requires: colord-kde-license = %{version}-%{release}

%description bin
bin components for the colord-kde package.


%package data
Summary: data components for the colord-kde package.
Group: Data

%description data
data components for the colord-kde package.


%package lib
Summary: lib components for the colord-kde package.
Group: Libraries
Requires: colord-kde-data = %{version}-%{release}
Requires: colord-kde-license = %{version}-%{release}

%description lib
lib components for the colord-kde package.


%package license
Summary: license components for the colord-kde package.
Group: Default

%description license
license components for the colord-kde package.


%package locales
Summary: locales components for the colord-kde package.
Group: Default

%description locales
locales components for the colord-kde package.


%prep
%setup -q -n colord-kde-0.5.0
cd %{_builddir}/colord-kde-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579716929
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1579716929
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/colord-kde
cp %{_builddir}/colord-kde-0.5.0/COPYING %{buildroot}/usr/share/package-licenses/colord-kde/4cc77b90af91e615a64ae04893fdffa7939db84c
pushd clr-build
%make_install
popd
%find_lang colord-kde

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/colord-kde-icc-importer

%files data
%defattr(-,root,root,-)
/usr/share/applications/colordkdeiccimporter.desktop
/usr/share/kservices5/kcm_colord.desktop
/usr/share/kservices5/kded/colord.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kcm_colord.so
/usr/lib64/qt5/plugins/kded_colord.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/colord-kde/4cc77b90af91e615a64ae04893fdffa7939db84c

%files locales -f colord-kde.lang
%defattr(-,root,root,-)

